name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  buildBot:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: restore
        run: dotnet restore .\MMOTFG_Bot\
      
      - name: execute build
        run: MSBuild.exe .\MMOTFG_Bot\MMOTFG_Bot\MMOTFG_Bot.csproj /p:Configuration=Release
  
  createFirebaseToken:
    needs: buildBot
    runs-on: ubuntu-latest
    steps:
      - name: createFile
        run: 
          touch .\MMOTFG_Bot\MMOTFG_Bot\assets\private\firebase-admin.json 
      - name: writeFile
        shell: bash
        run: echo "${{secrets.FIREBASE_TOKEN}}" >> .\MMOTFG_Bot\MMOTFG_Bot\assets\private\firebase-admin.json
          
  runBot:
    needs: createFirebaseToken
    runs-on: windows-latest
    steps:
      - name: arbolito
        run: tree
      - name: run
        run: .\MMOTFG_Bot\MMOTFG_Bot\bin\Release\netcoreapp3.1\MMOTFG_Bot.exe -t

          
