name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  buildAndTest:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: restore
        run: dotnet restore .\MMOTFG_Bot\
      
      - name: execute build
        run: MSBuild.exe .\MMOTFG_Bot\MMOTFG_Bot\MMOTFG_Bot.csproj /p:Configuration=Release

      - name: create private folder
        run: mkdir .\MMOTFG_Bot\MMOTFG_Bot\assets\private\

      - name: arbolito
        run: tree

      - name: createFile
        run: echo .\MMOTFG_Bot\MMOTFG_Bot\assets\private\firebase-admin.json 
      
      - name: writeFile
        run: echo "${{secrets.FIREBASE_TOKEN}}" >> .\MMOTFG_Bot\MMOTFG_Bot\assets\private\firebase-admin.json
      
      - name: go to exe dir
        run: cd .\MMOTFG_Bot\MMOTFG_Bot\bin\Release\netcoreapp3.1\
        
      - name: execute program
        run: ./MMOTFG_Bot.exe -t

     

          
